In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
df = pd.read_csv("../data/raw/googleplaystore.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [66]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [67]:
df.shape

(10841, 13)

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [69]:
df.describe(include="str").T

                count unique                 top   freq
App             10841   9660              ROBLOX      9
Category        10841     34              FAMILY   1972
Reviews         10841   6002                   0    596
Size            10841    462  Varies with device   1695
Installs        10841     22          1,000,000+   1579
Type            10840      3                Free  10039
Price           10841     93                   0  10040
Content Rating  10840      6            Everyone   8714
Genres          10841    120               Tools    842
Last Updated    10841   1378      August 3, 2018    326
Current Ver     10833   2832  Varies with device   1459
Android Ver     10838     33          4.1 and up   2451

In [70]:
df.describe().T

         count      mean       std  min  25%  50%  75%   max
Rating  9367.0  4.193338  0.537431  1.0  4.0  4.3  4.5  19.0

In [71]:
# Rating outside the expected range
df.loc[
    (df["Rating"].notnull()) &
    (~df["Rating"].between(1, 5)),
    ["App", "Rating"]
]

                                           App  Rating
10472  Life Made WI-Fi Touchscreen Photo Frame    19.0

In [72]:
quality_report = pd.DataFrame({
    "Data Type": df.dtypes.astype(str),
    "Missing Values": df.isnull().sum(),
    "Missing (%)": (df.isnull().mean() * 100).round(2),
    "Unique Values": df.nunique(),
    "Duplicate Values": df.duplicated().sum()
})

quality_report

,Data Type,Missing Values,Missing (%),Unique Values,Duplicate Values
App,str,0,0.00,9660,483
Category,str,0,0.00,34,483
Rating,float64,1474,13.60,40,483
Reviews,str,0,0.00,6002,483
Size,str,0,0.00,462,483
Installs,str,0,0.00,22,483
Type,str,1,0.01,3,483
Price,str,0,0.00,93,483
Content Rating,str,1,0.01,6,483
Genres,str,0,0.00,120,483
Last Updated,str,0,0.00,1378,483
Current Ver,str,8,0.07,2832,483
Android Ver,str,3,0.03,33,483

In [73]:
df.duplicated().sum()

np.int64(483)

In [74]:
df["Category"].value_counts()

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
COMICS                   60
PARENTING                60
BEAUTY                   53
1.9                       1
Name: count, dtype: int64

In [75]:
df["Type"].value_counts(dropna=False)

Type
Free    10039
Paid      800
NaN         1
0           1
Name: count, dtype: int64

In [76]:
df["Installs"].value_counts().head(10)

Installs
1,000,000+     1579
10,000,000+    1252
100,000+       1169
10,000+        1054
1,000+          907
5,000,000+      752
100+            719
500,000+        539
50,000+         479
5,000+          477
Name: count, dtype: int64

# Data Understanding : Google Play Store Dataset

## Overview & Dataset Dimensions
* **File Source:** `../data/raw/googleplaystore.csv`
* **Total Rows (Apps):** 10,841
* **Total Columns:** 13 features

---

## Dataset Structure & Features
The dataset contains 13 columns consisting of 12 String based and 1 float based
* **App:** The name of the mobile application.
* **Category:** The primary category the app belongs to. (Top 3 are FAMILY, GAMES and TOOLS)
* **Rating:** The user rating of the application on a scale from 1.0 to 5.0 (with data anomalies showing up to a max of 19.0)
* **Reviews:** The total number of user reviews submitted for the app.
* **Size:** The file size of the application (varying with device or listed in megabytes).
* **Installs:** The number of user downloads/installations.
* **Type:** Indicates whether the app is `Free` or `Paid`. 10039 are free and 800 paid
* **Price:** The monetary cost of the application.
* **Content Rating:** The target audience age group.
* **Genres:** Sub-categories or specific genre classifications.
* **Last Updated:** The date the application was last updated.
* **Current Ver:** The current version of the application.
* **Android Ver:** The minimum Android version required to run the app.

---

## Data Quality & Missing Value Analysis
A thorough check on missing entries and anomalies revealed the following:
* **Missing Values:**
  * `Rating` has 1,474 missing values (~13.60% of the dataset).
  * `Current Ver` has 8 missing values (~0.07%).
  * `Android Ver` has 3 missing values (~0.03%).
  * `Type` and `Content Rating` each have 1 missing value (~0.01%).
* **Duplicates:** The dataset contains **483 duplicate rows** that will need to be cleaned during preprocessing.
* **Data Anomalies:** The statistical summary for `Rating` reveals a data entry error where the `max` value is `19.0` (surpassing the standard 5.0 rating scale limit), requiring data cleaning and outlier handling.